# Generated by Django 3.2.9 on 2022-05-19 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signaturestorage',
            options={'verbose_name': '签名内容', 'verbose_name_plural': '签名内容'},
        ),
        migrations.RemoveField(
            model_name='contentstorage',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='signaturestorage',
            name='content',
        ),
        migrations.AddField(
            model_name='contentstorage',
            name='signature_location',
            field=models.TextField(default=0, max_length=500, verbose_name='签名位置'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docxinit',
            name='remote_sign',
            field=models.BooleanField(default=False, verbose_name='远程签名'),
        ),
        migrations.AddField(
            model_name='signaturestorage',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='确认签名'),
        ),
        migrations.AddField(
            model_name='signaturestorage',
            name='location',
            field=models.TextField(default=0, max_length=500, verbose_name='签名位置'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SignatureRemoteStorage',
            fields=[
                ('id', models.CharField(max_length=29, primary_key=True, serialize=False)),
                ('signature', models.TextField(blank=True, max_length=150000, verbose_name='签名')),
                ('is_download', models.BooleanField(default=False, verbose_name='是否下载')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='填写人')),
            ],
            options={
                'verbose_name': '签名',
                'verbose_name_plural': '签名',
            },
        ),
    ]
