# Generated by Django 3.2.9 on 2022-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20220519_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstorage',
            name='content_id',
            field=models.CharField(default=0, max_length=30, verbose_name='文件id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docxinit',
            name='docx_id',
            field=models.CharField(default=0, max_length=30, verbose_name='文件id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signatureremotestorage',
            name='signature_id',
            field=models.CharField(default=0, max_length=30, verbose_name='签名id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signaturestorage',
            name='signature_id',
            field=models.CharField(default=0, max_length=30, verbose_name='签名id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentstorage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docxinit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signatureremotestorage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signaturestorage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
