# Generated by Django 3.2.9 on 2022-05-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20220523_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatureremotestorage',
            name='download_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下载时间'),
        ),
        migrations.AddField(
            model_name='signatureremotestorage',
            name='key',
            field=models.CharField(default=0, max_length=30, verbose_name='密钥'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contentstorage',
            name='content_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='文件id'),
        ),
        migrations.AlterField(
            model_name='docxinit',
            name='docx_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='文件id'),
        ),
        migrations.AlterField(
            model_name='signatureremotestorage',
            name='signature_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='签名id'),
        ),
        migrations.AlterField(
            model_name='signaturestorage',
            name='signature_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='签名id'),
        ),
    ]
