# Generated by Django 3.2.9 on 2022-05-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20220525_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentstorage',
            name='signature_location',
        ),
        migrations.RemoveField(
            model_name='signaturestorage',
            name='is_confirm',
        ),
        migrations.RemoveField(
            model_name='signaturestorage',
            name='location',
        ),
        migrations.AddField(
            model_name='contentstorage',
            name='signature_id',
            field=models.TextField(default=0, max_length=500, verbose_name='签名号'),
            preserve_default=False,
        ),
    ]
