# Generated by Django 3.2.9 on 2022-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20220526_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstorage',
            name='signature_id',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='签名号'),
        ),
    ]
