# Generated by Django 3.2.9 on 2022-05-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_alter_contentstorage_signature_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentstorage',
            name='is_confirm',
            field=models.BooleanField(default=False, verbose_name='签字确认'),
        ),
    ]
