# Generated by Django 3.2.9 on 2022-05-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_contentstorage_is_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentstorage',
            name='signature_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='签名号'),
        ),
    ]
