# Generated by Django 3.2.9 on 2022-03-03 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight', models.CharField(max_length=30, verbose_name='航班号')),
                ('date', models.DateField(verbose_name='日期')),
                ('destination', models.CharField(max_length=30, verbose_name='目的地')),
            ],
            options={
                'verbose_name': '舱单',
                'verbose_name_plural': '舱单',
            },
        ),
        migrations.CreateModel(
            name='LoadSheetContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(choices=[('旅客', '旅客'), ('行李', '行李'), ('其他', '其他')], max_length=300, verbose_name='项目')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('type', models.CharField(blank=True, choices=[('', '无'), ('成人', '成人'), ('儿童', '儿童'), ('婴儿', '婴儿'), ('机组', '机组'), ('货', '货'), ('邮', '邮'), ('压舱物', '压舱物')], max_length=300, null=True, verbose_name='类型')),
                ('_class', models.CharField(blank=True, choices=[('', '无'), ('Y', 'Y'), ('W', 'W'), ('C', 'C'), ('F', 'F')], max_length=300, null=True, verbose_name='舱位')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='位置')),
                ('weight', models.IntegerField(verbose_name='重量')),
                ('load_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadSheet_load_sheet', to='flexible.loadsheet', verbose_name='舱单')),
            ],
            options={
                'verbose_name': '舱单内容',
                'verbose_name_plural': '舱单内容',
            },
        ),
    ]
