# Generated by Django 3.2.9 on 2022-04-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight', models.CharField(max_length=30, verbose_name='航班号')),
                ('date', models.DateField(verbose_name='日期')),
                ('destination', models.CharField(max_length=30, verbose_name='目的地')),
                ('aircraft', models.CharField(max_length=30, verbose_name='机型')),
                ('passenger', models.IntegerField(blank=True, null=True, verbose_name='旅客人数')),
                ('baggage', models.IntegerField(blank=True, null=True, verbose_name='行李件数')),
                ('ACARS', models.BooleanField(default=False, verbose_name='上传ACARS')),
                ('EFB', models.BooleanField(default=False, verbose_name='上传EFB')),
                ('description', models.TextField(max_length=1000, verbose_name='描述')),
            ],
            options={
                'verbose_name': '舱单',
                'verbose_name_plural': '舱单',
            },
        ),
        migrations.CreateModel(
            name='LoadSheetContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination', models.CharField(blank=True, max_length=30, null=True, verbose_name='目的地')),
                ('project', models.CharField(choices=[('旅客', '旅客'), ('行李', '行李'), ('其他', '其他')], max_length=30, verbose_name='项目')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('type', models.CharField(blank=True, choices=[('', '无'), ('成人', '成人'), ('儿童', '儿童'), ('婴儿', '婴儿'), ('机组', '机组'), ('货', '货'), ('邮', '邮'), ('压舱物', '压舱物')], max_length=30, null=True, verbose_name='类型')),
                ('_class', models.CharField(blank=True, choices=[('', '无'), ('Y', 'Y'), ('W', 'W'), ('J', 'J'), ('F', 'F')], max_length=30, null=True, verbose_name='舱位')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='位置')),
                ('weight', models.IntegerField(verbose_name='重量')),
            ],
            options={
                'verbose_name': '舱单内容',
                'verbose_name_plural': '舱单内容',
            },
        ),
        migrations.CreateModel(
            name='LoadSheetRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('anonymous', models.CharField(blank=True, max_length=300, null=True, verbose_name='未登录用户')),
                ('times', models.IntegerField(blank=True, null=True, verbose_name='参与次数')),
                ('answer_time', models.IntegerField(blank=True, null=True, verbose_name='答题时长')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='成绩')),
                ('submit_datetime', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('load_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadSheetRecord_load_sheet', to='flexible.loadsheet', verbose_name='舱单')),
            ],
            options={
                'verbose_name': '舱单成绩记录',
                'verbose_name_plural': '舱单成绩记录',
            },
        ),
    ]
