# Generated by Django 3.2.9 on 2022-04-29 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsheetrecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loadSheetRecord_user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='loadsheetcontent',
            name='load_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadSheet_load_sheet', to='flexible.loadsheet', verbose_name='舱单'),
        ),
    ]
