# Generated by Django 3.2.9 on 2022-02-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customteam',
            name='related_parent',
            field=models.JSONField(blank=True, max_length=300, null=True, verbose_name='组织关系'),
        ),
    ]
