# Generated by Django 3.2.6 on 2021-09-08 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='处罚类别')),
            ],
            options={
                'verbose_name': '处罚类别',
                'verbose_name_plural': '处罚类别',
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='岗位及特殊岗位类别')),
            ],
            options={
                'verbose_name': '岗位及特殊岗位类别',
                'verbose_name_plural': '岗位及特殊岗位类别',
            },
        ),
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖惩类别')),
            ],
            options={
                'verbose_name': '奖励类别',
                'verbose_name_plural': '奖励类别',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖励名称')),
                ('score', models.FloatField(verbose_name='奖励分数')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.rewardtype', verbose_name='奖励类别')),
            ],
            options={
                'verbose_name': '奖励',
                'verbose_name_plural': '奖励',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='岗位及特殊岗位名称')),
                ('score', models.FloatField(verbose_name='岗位及特殊岗位分数')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.positiontype', verbose_name='岗位及特殊岗位类别')),
            ],
            options={
                'verbose_name': '岗位及特殊岗位',
                'verbose_name_plural': '岗位及特殊岗位',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='处罚名称')),
                ('score', models.FloatField(verbose_name='处罚分数')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.rewardtype', verbose_name='处罚类别')),
            ],
            options={
                'verbose_name': '处罚',
                'verbose_name_plural': '处罚',
            },
        ),
    ]
