# Generated by Django 3.2.6 on 2021-09-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='程度规则名称')),
                ('calculation', models.CharField(max_length=100, verbose_name='计算方式')),
            ],
            options={
                'verbose_name': '程度加成规则设置',
                'verbose_name_plural': '程度加成规则设置',
            },
        ),
        migrations.CreateModel(
            name='RepeatRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='重复规则名称')),
                ('day', models.IntegerField(default=0, verbose_name='天数')),
                ('calculation', models.CharField(max_length=100, verbose_name='计算方式')),
            ],
            options={
                'verbose_name': '重复规则设置',
                'verbose_name_plural': '重复规则设置',
            },
        ),
        migrations.CreateModel(
            name='SaleRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='销量规则名称')),
                ('require', models.CharField(max_length=100, verbose_name='要求量')),
                ('calculation', models.CharField(max_length=100, verbose_name='计算方式')),
            ],
            options={
                'verbose_name': '销量规则设置',
                'verbose_name_plural': '销量规则设置',
            },
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, verbose_name='岗位及特殊岗位名称'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='level_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.levelrule', verbose_name='程度加成规则'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='repeat_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.repeatrule', verbose_name='重复规则'),
        ),
        migrations.AddField(
            model_name='position',
            name='sale_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.salerule', verbose_name='销量加成规则'),
        ),
        migrations.AddField(
            model_name='reward',
            name='level_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.levelrule', verbose_name='程度加成规则'),
        ),
        migrations.AddField(
            model_name='reward',
            name='repeat_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.repeatrule', verbose_name='重复规则'),
        ),
    ]
