# Generated by Django 3.2.9 on 2021-12-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_auto_20211230_1416'),
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPenalty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖惩名称')),
                ('score', models.FloatField(verbose_name='奖惩分数')),
                ('repeat_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.repeatrule', verbose_name='重复规则')),
            ],
            options={
                'verbose_name': '奖励',
                'verbose_name_plural': '奖励',
            },
        ),
        migrations.CreateModel(
            name='WorkloadItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='项目')),
                ('weight', models.FloatField(verbose_name='每单位折算收入')),
            ],
            options={
                'verbose_name': '绩效项目',
                'verbose_name_plural': '绩效项目',
            },
        ),
        migrations.RemoveField(
            model_name='reward',
            name='repeat_rule',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='type',
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '岗位', 'verbose_name_plural': '岗位'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='sale_rule',
        ),
        migrations.RemoveField(
            model_name='position',
            name='type',
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, verbose_name='岗位名称'),
        ),
        migrations.AlterField(
            model_name='position',
            name='score',
            field=models.FloatField(verbose_name='岗位分数'),
        ),
        migrations.RenameModel(
            old_name='RewardType',
            new_name='RewardPenaltyType',
        ),
        migrations.DeleteModel(
            name='Penalty',
        ),
        migrations.DeleteModel(
            name='PenaltyType',
        ),
        migrations.DeleteModel(
            name='PositionType',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.AddField(
            model_name='workloaditem',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.position', verbose_name='所属岗位'),
        ),
        migrations.AddField(
            model_name='rewardpenalty',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.rewardpenaltytype', verbose_name='奖励类别'),
        ),
    ]
