# Generated by Django 3.2.6 on 2021-09-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20210909_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='level_rule',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='level_rule',
        ),
    ]
