# Generated by Django 3.2.9 on 2022-03-03 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='阅读人'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='announcement_people', to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='announcement_team', to='team.CustomTeam', verbose_name='目标组'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_user', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.CreateModel(
            name='AnnouncementRecordSummary',
            fields=[
            ],
            options={
                'verbose_name': '确认统计',
                'verbose_name_plural': '确认统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('announcement.announcement',),
        ),
    ]
