# Generated by Django 3.2.9 on 2022-02-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_announcement_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='repeat_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='重复天数'),
        ),
    ]
