# Generated by Django 3.2.9 on 2022-02-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='流动资产编号')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='流动资产名称')),
            ],
            options={
                'verbose_name': '流动资产设置',
                'verbose_name_plural': '流动资产设置',
            },
        ),
        migrations.CreateModel(
            name='CurrentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='流动资产类型')),
            ],
            options={
                'verbose_name': '流动资产类型设置',
                'verbose_name_plural': '流动资产类型设置',
            },
        ),
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='固定资产编号')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='固定资产名称')),
                ('expiry_date', models.DateField(null=True, verbose_name='过期日期')),
            ],
            options={
                'verbose_name': '固定资产管理',
                'verbose_name_plural': '固定资产管理',
            },
        ),
        migrations.CreateModel(
            name='FixedStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='状态名称')),
            ],
            options={
                'verbose_name': '状态设置',
                'verbose_name_plural': '状态设置',
            },
        ),
        migrations.CreateModel(
            name='FixedType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='固定资产类型')),
            ],
            options={
                'verbose_name': '固定资产类型设置',
                'verbose_name_plural': '固定资产类型设置',
            },
        ),
        migrations.CreateModel(
            name='RoomPurpose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='用途名称')),
            ],
            options={
                'verbose_name': '房间用途设置',
                'verbose_name_plural': '房间用途设置',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='房间编号')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='房间名称')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_purpose', to='asset.roompurpose', verbose_name='用途')),
            ],
            options={
                'verbose_name': '房间设置',
                'verbose_name_plural': '房间设置',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fixed', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_fixed', to='asset.fixed', verbose_name='货架对应资产')),
                ('room', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_room', to='asset.room', verbose_name='位置')),
            ],
            options={
                'verbose_name': '管理货架',
                'verbose_name_plural': '管理货架',
                'ordering': ['room__name', 'fixed__name'],
            },
        ),
        migrations.AddField(
            model_name='fixed',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_room', to='asset.room', verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_status', to='asset.fixedstatus', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='fixed',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_type', to='asset.fixedtype', verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='CurrentStorage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='库存数量')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentStorage_current', to='asset.current', verbose_name='物资名称')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentStorage_rack', to='asset.rack', verbose_name='所在货架')),
            ],
            options={
                'verbose_name': '流动资产库存',
                'verbose_name_plural': '流动资产库存',
            },
        ),
        migrations.CreateModel(
            name='CurrentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(verbose_name='出入库数量')),
                ('in_out', models.CharField(choices=[('入库', '入库'), ('出库', '出库')], max_length=300, verbose_name='出入库')),
                ('operating_datetime', models.DateTimeField(auto_now=True, verbose_name='最新操作时间')),
                ('comment', models.TextField(blank=True, max_length=300, verbose_name='备注')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currentRecord_current', to='asset.current', verbose_name='流动资产名称')),
            ],
            options={
                'verbose_name': '流动资产入出库记录',
                'verbose_name_plural': '流动资产入出库记录',
            },
        ),
    ]
