# Generated by Django 3.2.9 on 2022-05-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSummary',
            fields=[
            ],
            options={
                'verbose_name': '工时统计',
                'verbose_name_plural': '工时统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('asset.currentrecord',),
        ),
        migrations.AlterModelOptions(
            name='current',
            options={'verbose_name': '设置-流动资产', 'verbose_name_plural': '设置-流动资产'},
        ),
        migrations.AlterModelOptions(
            name='currenttype',
            options={'verbose_name': '设置-流动资产类型', 'verbose_name_plural': '设置-流动资产类型'},
        ),
        migrations.AlterModelOptions(
            name='fixed',
            options={'verbose_name': '设置-固定资产', 'verbose_name_plural': '设置-固定资产'},
        ),
        migrations.AlterModelOptions(
            name='fixedstatus',
            options={'verbose_name': '设置-资产使用状态', 'verbose_name_plural': '设置-资产使用状态'},
        ),
        migrations.AlterModelOptions(
            name='fixedtype',
            options={'verbose_name': '设置-固定资产类型', 'verbose_name_plural': '设置-固定资产类型'},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['room__name', 'fixed__name'], 'verbose_name': '管理-存放位置', 'verbose_name_plural': '管理-存放位置'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '设置-房间', 'verbose_name_plural': '设置-房间'},
        ),
        migrations.AlterModelOptions(
            name='roompurpose',
            options={'verbose_name': '设置-房间用途', 'verbose_name_plural': '设置-房间用途'},
        ),
        migrations.AddField(
            model_name='current',
            name='unit',
            field=models.CharField(default=0, max_length=30, verbose_name='单位'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentrecord',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='出入库数量'),
        ),
    ]
