# Generated by Django 3.2.9 on 2022-03-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed',
            name='name',
            field=models.CharField(max_length=300, verbose_name='固定资产名称'),
        ),
    ]
