# Generated by Django 3.2.9 on 2022-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_fixed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='sn',
            field=models.CharField(default=0, max_length=300, verbose_name='流动资产编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixed',
            name='sn',
            field=models.CharField(default=0, max_length=300, verbose_name='固定资产编号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='sn',
            field=models.CharField(default=0, max_length=300, verbose_name='房间编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='current',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fixed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
