# Generated by Django 3.2.9 on 2022-05-31 08:55

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20220530_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentsummary',
            options={'verbose_name': '流动资产入出库统计', 'verbose_name_plural': '流动资产入出库统计'},
        ),
        migrations.AlterModelOptions(
            name='fixedstatus',
            options={'verbose_name': '设置-固定资产状态', 'verbose_name_plural': '设置-固定资产状态'},
        ),
        migrations.AlterField(
            model_name='current',
            name='name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300, unique=True, verbose_name='流动资产名称')),
        ),
    ]
