# Generated by Django 3.2.9 on 2022-03-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20220330_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixed',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='过期日期'),
        ),
    ]
