# Generated by Django 3.2.9 on 2022-03-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20220330_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='fixed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_fixed', to='asset.fixed', verbose_name='对应固定资产'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_room', to='asset.room', verbose_name='堆放地'),
        ),
    ]
