# Generated by Django 3.2.9 on 2022-04-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, max_length=1000, null=True, verbose_name='标题')),
                ('content', models.TextField(max_length=100000, verbose_name='内容')),
                ('submit_datetime', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
                ('related_post', models.JSONField(blank=True, max_length=300, null=True, verbose_name='回复关系')),
                ('parent_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bbs.post', verbose_name='回复对象')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
    ]
