# Generated by Django 3.2.9 on 2022-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_post',
            field=models.JSONField(blank=True, max_length=300, null=True, verbose_name='回复关系'),
        ),
    ]
