# Generated by Django 3.2.6 on 2021-09-08 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cost', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costrecord',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costRecord_user', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='costrecord',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costRecord_team', to='team.customteam', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='cost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.costtype', verbose_name='成本'),
        ),
    ]
