# Generated by Django 3.2.9 on 2022-03-04 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cost', '0001_initial'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='costrecord',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costRecord_create_user', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='costrecord',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costRecord_team', to='team.customteam', verbose_name='团队'),
        ),
        migrations.AddField(
            model_name='cost',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.costtype', verbose_name='成本类别'),
        ),
        migrations.CreateModel(
            name='CostSummary',
            fields=[
            ],
            options={
                'verbose_name': '团队表现统计',
                'verbose_name_plural': '团队表现统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cost.costrecord',),
        ),
    ]
