# Generated by Django 3.2.9 on 2021-12-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': '成本设置', 'verbose_name_plural': '成本设置'},
        ),
        migrations.AlterModelOptions(
            name='costsummary',
            options={'verbose_name': '团队表现统计', 'verbose_name_plural': '团队表现统计'},
        ),
    ]
