# Generated by Django 3.2.7 on 2021-09-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSummary',
            fields=[
            ],
            options={
                'verbose_name': '成本统计',
                'verbose_name_plural': '成本统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cost.costrecord',),
        ),
    ]
