# Generated by Django 3.2.9 on 2022-02-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManHourItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='项目')),
                ('weight', models.FloatField(verbose_name='每单位折算产出')),
            ],
            options={
                'verbose_name': '工时项目',
                'verbose_name_plural': '工时项目',
            },
        ),
        migrations.CreateModel(
            name='ManHourRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(verbose_name='开始时间')),
                ('end_datetime', models.DateTimeField(verbose_name='结束时间')),
                ('remark', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('verify', models.BooleanField(default=False, verbose_name='审核状态')),
                ('verify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '工时登记记录',
                'verbose_name_plural': '工时登记记录',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
            },
        ),
        migrations.CreateModel(
            name='WorkloadItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='项目')),
                ('weight', models.FloatField(verbose_name='每单位折算产出')),
            ],
            options={
                'verbose_name': '工作量项目',
                'verbose_name_plural': '工作量项目',
            },
        ),
        migrations.CreateModel(
            name='WorkloadRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('workload', models.JSONField(blank=True, max_length=1000, verbose_name='项目')),
                ('remark', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('verify', models.BooleanField(default=False, verbose_name='审核状态')),
                ('verify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.position', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '工作量登记记录',
                'verbose_name_plural': '工作量登记记录',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
