# Generated by Django 3.2.6 on 2021-09-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='加成后处罚分数')),
                ('title', models.CharField(max_length=500, verbose_name='简述')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='详细情况')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '处罚记录',
                'verbose_name_plural': '处罚记录',
            },
        ),
        migrations.CreateModel(
            name='RewardRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='加成后奖励分数')),
                ('title', models.CharField(max_length=500, verbose_name='简述')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='详细情况')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '奖励记录',
                'verbose_name_plural': '奖励记录',
            },
        ),
        migrations.CreateModel(
            name='WorkloadRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('number_people', models.IntegerField(default=0, verbose_name='办理人数')),
                ('number_baggage', models.IntegerField(default=0, verbose_name='办理行李')),
                ('sale', models.FloatField(default=0, verbose_name='销售额')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='销售额加成后分数')),
                ('remark', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('verify', models.BooleanField(default=False, verbose_name='审核状态')),
                ('verify_datetime', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.position', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '工作量登记记录',
                'verbose_name_plural': '工作量登记记录',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
