# Generated by Django 3.2.9 on 2021-12-30 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rule', '0001_initial'),
        ('performance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPenaltyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='加成后奖惩分数')),
                ('title', models.CharField(max_length=500, verbose_name='简述')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='详细情况')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('level_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.levelrule', verbose_name='程度加成规则')),
            ],
            options={
                'verbose_name': '奖惩记录',
                'verbose_name_plural': '奖惩记录',
            },
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='level_rule',
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='penalty',
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rewardrecord',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='rewardrecord',
            name='level_rule',
        ),
        migrations.RemoveField(
            model_name='rewardrecord',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='rewardrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='PenaltySummary',
        ),
        migrations.DeleteModel(
            name='RewardSummary',
        ),
        migrations.RemoveField(
            model_name='workloadrecord',
            name='number_baggage',
        ),
        migrations.RemoveField(
            model_name='workloadrecord',
            name='number_people',
        ),
        migrations.RemoveField(
            model_name='workloadrecord',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='workloadrecord',
            name='score',
        ),
        migrations.AddField(
            model_name='workloadrecord',
            name='workload',
            field=models.JSONField(blank=True, default=0, max_length=1000, verbose_name='项目'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PenaltyRecord',
        ),
        migrations.DeleteModel(
            name='RewardRecord',
        ),
    ]
