# Generated by Django 3.2.6 on 2021-09-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadrecord',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='销售额加成后分数'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='加成后处罚分数'),
        ),
        migrations.AlterField(
            model_name='rewardrecord',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='加成后奖励分数'),
        ),
    ]
