# Generated by Django 3.2.9 on 2021-12-30 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0003_auto_20211230_1416'),
        ('rule', '0002_auto_20211230_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpenaltyrecord',
            name='reward_penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.rewardpenalty', verbose_name='奖惩项'),
        ),
        migrations.AddField(
            model_name='rewardpenaltyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewardPenaltyRecord_user', to=settings.AUTH_USER_MODEL, verbose_name='奖励人'),
        ),
        migrations.CreateModel(
            name='RewardPenaltySummary',
            fields=[
            ],
            options={
                'verbose_name': '奖惩统计',
                'verbose_name_plural': '奖励统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('performance.rewardpenaltyrecord',),
        ),
    ]
