# Generated by Django 3.2.6 on 2021-09-09 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0003_auto_20210909_1040'),
        ('performance', '0003_auto_20210909_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyrecord',
            name='level_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.levelrule', verbose_name='程度加成规则'),
        ),
        migrations.AddField(
            model_name='rewardrecord',
            name='level_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rule.levelrule', verbose_name='程度加成规则'),
        ),
    ]
