# Generated by Django 3.2.7 on 2021-09-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_auto_20210909_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardsummary',
            options={'verbose_name': '奖惩统计', 'verbose_name_plural': '奖励统计'},
        ),
    ]
