# Generated by Django 3.2.9 on 2022-02-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='服务名称')),
            ],
            options={
                'verbose_name': '服务名称',
                'verbose_name_plural': '服务名称',
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('score', models.FloatField(verbose_name='得分')),
                ('fill_datetime', models.DateTimeField(blank=True, null=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '服务满意度得分',
                'verbose_name_plural': '服务满意度得分',
            },
        ),
    ]
