# Generated by Django 3.2.7 on 2021-09-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSummary',
            fields=[
            ],
            options={
                'verbose_name': '个人表现统计',
                'verbose_name_plural': '个人表现统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('performance.workloadrecord',),
        ),
    ]
