# Generated by Django 3.2.9 on 2022-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='程度规则名称')),
                ('calculation', models.CharField(max_length=100, verbose_name='计算方式')),
            ],
            options={
                'verbose_name': '程度加成规则设置',
                'verbose_name_plural': '程度加成规则设置',
            },
        ),
        migrations.CreateModel(
            name='RepeatRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='重复规则名称')),
                ('day', models.IntegerField(default=0, verbose_name='天数')),
                ('calculation', models.CharField(max_length=100, verbose_name='计算方式')),
            ],
            options={
                'verbose_name': '重复规则设置',
                'verbose_name_plural': '重复规则设置',
            },
        ),
        migrations.CreateModel(
            name='RewardPenalty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖惩名称')),
                ('score', models.FloatField(verbose_name='奖惩分数')),
            ],
            options={
                'verbose_name': '奖励',
                'verbose_name_plural': '奖励',
            },
        ),
        migrations.CreateModel(
            name='RewardPenaltyRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='加成后奖惩分数')),
                ('title', models.CharField(max_length=500, verbose_name='简述')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='详细情况')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
            ],
            options={
                'verbose_name': '奖惩记录',
                'verbose_name_plural': '奖惩记录',
            },
        ),
        migrations.CreateModel(
            name='RewardPenaltyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖惩类别')),
            ],
            options={
                'verbose_name': '奖励类别',
                'verbose_name_plural': '奖励类别',
            },
        ),
    ]
