# Generated by Django 3.2.9 on 2022-03-30 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpenaltyrecord',
            name='create_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='rewardpenaltyrecord',
            name='level_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.levelrule', verbose_name='程度加成规则'),
        ),
        migrations.AddField(
            model_name='rewardpenaltyrecord',
            name='reward_penalty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.rewardpenalty', verbose_name='奖惩项'),
        ),
        migrations.AddField(
            model_name='rewardpenaltyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewardPenaltyRecord_user', to=settings.AUTH_USER_MODEL, verbose_name='奖励人'),
        ),
        migrations.AddField(
            model_name='rewardpenalty',
            name='repeat_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reward.repeatrule', verbose_name='重复规则'),
        ),
        migrations.AddField(
            model_name='rewardpenalty',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.rewardpenaltytype', verbose_name='奖励类别'),
        ),
        migrations.CreateModel(
            name='RewardPenaltySummary',
            fields=[
            ],
            options={
                'verbose_name': '奖惩统计',
                'verbose_name_plural': '奖励统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reward.rewardpenaltyrecord',),
        ),
    ]
