# Generated by Django 3.2.6 on 2021-09-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['team__name']},
        ),
    ]
