# Generated by Django 3.2.7 on 2021-09-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['team__name'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
