# Generated by Django 3.2.9 on 2022-02-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='课程类别名称')),
            ],
            options={
                'verbose_name': '课程类别',
                'verbose_name_plural': '课程类别',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='培训日期')),
                ('expiry_date', models.DateField(verbose_name='到期日期')),
                ('teacher', models.CharField(blank=True, max_length=300, verbose_name='讲师')),
                ('remind', models.BooleanField(default=False, verbose_name='是否提醒复训')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.course', verbose_name='培训名称')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
            },
        ),
    ]
