# Generated by Django 3.2.7 on 2021-09-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='培训类别')),
            ],
            options={
                'verbose_name': '培训类别',
                'verbose_name_plural': '培训类别',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='培训名称')),
                ('date', models.DateField(verbose_name='培训日期')),
                ('expiration_date', models.DateField(verbose_name='到期日期')),
                ('remind_retraining', models.BooleanField(default=False, verbose_name='是否提醒复训')),
                ('retraining_period', models.IntegerField(default=0, verbose_name='提示周期天数')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingtype', verbose_name='培训类别')),
            ],
            options={
                'verbose_name': '培训',
                'verbose_name_plural': '培训',
            },
        ),
    ]
