# Generated by Django 3.2.6 on 2021-09-13 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='training_user', to=settings.AUTH_USER_MODEL, verbose_name='培训对象'),
        ),
    ]
