# Generated by Django 3.2.6 on 2021-09-08 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='training_user', to=settings.AUTH_USER_MODEL, verbose_name='培训对象'),
        ),
        migrations.AddField(
            model_name='training',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingtype', verbose_name='培训类别'),
        ),
    ]
