# Generated by Django 3.2.6 on 2021-09-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_date',
            new_name='date',
        ),
    ]
