# Generated by Django 3.2.6 on 2021-09-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_rename_training_date_training_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='student',
            new_name='user',
        ),
    ]
